### ISSUE TITLE
⚙️ Build side menu for 0xhabitat.org

### ISSUE THREAD

**Issue by MaxKuck** [0xHabitat/habitat#29]
## Scope

- build menu for 0xhabitat.org
![image](https://user-images.githubusercontent.com/45236782/109311943-bc78a880-7846-11eb-9a36-7e001468cf57.png)

 https://www.figma.com/file/vYIiWTuvQsAyb821lkmu7J/Habitat?node-id=90%3A266
links to (0xhabitat.org + 0xhabitat.org/evolution + 0xhabitat.org/token

## Deliverables

- deployment when token bootstrap page is pushed

## Funding Circle

- deora/habitat

## Bounty Owner/Gardener

@MaxKuck 

## Roles
bounty gardener: @MaxKuck (-)
bounty worker: @troggy (... DAI)
bounty reviewer: name / share

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

- [x] build draft in figma board

**Comment by MaxKuck** [comment]
love it @troggy nice work! let's talk on the daily about compensation :)

**Comment by troggy** [comment]
Peeps, requesting a 200 DAI worth of HBT for this work :—)
