### ISSUE TITLE
Good Feeling: Long 🍌squeeze button

### ISSUE THREAD

**Issue by pinkiebell** [0xHabitat/habitat#57]
### ⚡️ Challenge:
Design & Implement a `Good Feeling` button that longs bananas and therefore squeezes supply.

Apes should be productive in habitata land, but also having fun interacting with the community while working.
Even if this leads to banana shakes and the resulting supply shortage, this idea helps in team building and is therefore really more important than productivity. 🦧✋5

### 🦋 Desired Outcome
More fun in habitata land.

### 🎯 Action Points:
Let the button randomly appear in the user interface.

### 🐇 Additional Information
Insider. But imagine 🍌squeezing out of the button all over the interface. 🦧🙌

**Comment by 0x-vic** [comment]
### First Submission for Review :)

3 Screen User Journey with 3 Buttons clickable:
* "Feeling Bored Today?" - grey
* "Want To Long Bananas?" - grey
* "Good Feeling" - green

Draft attached:
![storyboard-longsqueeze](https://user-images.githubusercontent.com/55283710/119018453-61b1a180-b99c-11eb-9b35-3f2f11cc372b.jpg)

**Comment by pinkiebell** [comment]
🤣🦾
